# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trading_api_pb2 as trading__api__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/bot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BotServiceStub(object):
    """BotService provides a focused interface for bot lifecycle operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBot = channel.unary_unary(
                '/trading.BotService/CreateBot',
                request_serializer=trading__api__pb2.CreateBotRequest.SerializeToString,
                response_deserializer=trading__api__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListBots = channel.unary_unary(
                '/trading.BotService/ListBots',
                request_serializer=trading__api__pb2.Empty.SerializeToString,
                response_deserializer=trading__api__pb2.BotList.FromString,
                _registered_method=True)
        self.StartBot = channel.unary_unary(
                '/trading.BotService/StartBot',
                request_serializer=trading__api__pb2.BotIdRequest.SerializeToString,
                response_deserializer=trading__api__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StopBot = channel.unary_unary(
                '/trading.BotService/StopBot',
                request_serializer=trading__api__pb2.BotIdRequest.SerializeToString,
                response_deserializer=trading__api__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetBotStatus = channel.unary_unary(
                '/trading.BotService/GetBotStatus',
                request_serializer=trading__api__pb2.BotIdRequest.SerializeToString,
                response_deserializer=trading__api__pb2.BotConfig.FromString,
                _registered_method=True)


class BotServiceServicer(object):
    """BotService provides a focused interface for bot lifecycle operations.
    """

    def CreateBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBotStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBot,
                    request_deserializer=trading__api__pb2.CreateBotRequest.FromString,
                    response_serializer=trading__api__pb2.StatusResponse.SerializeToString,
            ),
            'ListBots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBots,
                    request_deserializer=trading__api__pb2.Empty.FromString,
                    response_serializer=trading__api__pb2.BotList.SerializeToString,
            ),
            'StartBot': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBot,
                    request_deserializer=trading__api__pb2.BotIdRequest.FromString,
                    response_serializer=trading__api__pb2.StatusResponse.SerializeToString,
            ),
            'StopBot': grpc.unary_unary_rpc_method_handler(
                    servicer.StopBot,
                    request_deserializer=trading__api__pb2.BotIdRequest.FromString,
                    response_serializer=trading__api__pb2.StatusResponse.SerializeToString,
            ),
            'GetBotStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBotStatus,
                    request_deserializer=trading__api__pb2.BotIdRequest.FromString,
                    response_serializer=trading__api__pb2.BotConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.BotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading.BotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotService(object):
    """BotService provides a focused interface for bot lifecycle operations.
    """

    @staticmethod
    def CreateBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.BotService/CreateBot',
            trading__api__pb2.CreateBotRequest.SerializeToString,
            trading__api__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.BotService/ListBots',
            trading__api__pb2.Empty.SerializeToString,
            trading__api__pb2.BotList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.BotService/StartBot',
            trading__api__pb2.BotIdRequest.SerializeToString,
            trading__api__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.BotService/StopBot',
            trading__api__pb2.BotIdRequest.SerializeToString,
            trading__api__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBotStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.BotService/GetBotStatus',
            trading__api__pb2.BotIdRequest.SerializeToString,
            trading__api__pb2.BotConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
