# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/bot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/bot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import trading_api_pb2 as trading__api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/bot.proto\x12\x07trading\x1a\x11trading_api.proto\"\xe5\x01\n\tBotConfig\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\x12\x36\n\nparameters\x18\x04 \x03(\x0b\x32\".trading.BotConfig.ParametersEntry\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x1a\n\x12\x63reated_at_unix_ms\x18\x06 \x01(\x03\x12\x0c\n\x04name\x18\x07 \x01(\t\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb4\x01\n\x10\x43reateBotRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08strategy\x18\x02 \x01(\t\x12=\n\nparameters\x18\x03 \x03(\x0b\x32).trading.CreateBotRequest.ParametersEntry\x12\x0c\n\x04name\x18\x04 \x01(\t\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1e\n\x0c\x42otIdRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\"+\n\x07\x42otList\x12 \n\x04\x62ots\x18\x01 \x03(\x0b\x32\x12.trading.BotConfig2\xb7\x02\n\nBotService\x12\x41\n\tCreateBot\x12\x19.trading.CreateBotRequest\x1a\x17.trading.StatusResponse\"\x00\x12.\n\x08ListBots\x12\x0e.trading.Empty\x1a\x10.trading.BotList\"\x00\x12<\n\x08StartBot\x12\x15.trading.BotIdRequest\x1a\x17.trading.StatusResponse\"\x00\x12;\n\x07StopBot\x12\x15.trading.BotIdRequest\x1a\x17.trading.StatusResponse\"\x00\x12;\n\x0cGetBotStatus\x12\x15.trading.BotIdRequest\x1a\x12.trading.BotConfig\"\x00\x42-Z+github.com/rwh9609-bit/multilanguage/go/genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.bot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/rwh9609-bit/multilanguage/go/gen'
  _globals['_BOTCONFIG_PARAMETERSENTRY']._loaded_options = None
  _globals['_BOTCONFIG_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_CREATEBOTREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_CREATEBOTREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_BOTCONFIG']._serialized_start=49
  _globals['_BOTCONFIG']._serialized_end=278
  _globals['_BOTCONFIG_PARAMETERSENTRY']._serialized_start=229
  _globals['_BOTCONFIG_PARAMETERSENTRY']._serialized_end=278
  _globals['_CREATEBOTREQUEST']._serialized_start=281
  _globals['_CREATEBOTREQUEST']._serialized_end=461
  _globals['_CREATEBOTREQUEST_PARAMETERSENTRY']._serialized_start=229
  _globals['_CREATEBOTREQUEST_PARAMETERSENTRY']._serialized_end=278
  _globals['_BOTIDREQUEST']._serialized_start=463
  _globals['_BOTIDREQUEST']._serialized_end=493
  _globals['_BOTLIST']._serialized_start=495
  _globals['_BOTLIST']._serialized_end=538
  _globals['_BOTSERVICE']._serialized_start=541
  _globals['_BOTSERVICE']._serialized_end=852
# @@protoc_insertion_point(module_scope)
