FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install --legacy-peer-deps || npm install
RUN npm install react-chartjs-2 chart.js
COPY frontend/ .
ARG REACT_APP_GRPC_HOST
ENV REACT_APP_GRPC_HOST=${REACT_APP_GRPC_HOST}
RUN echo "REACT_APP_GRPC_HOST is set to: $REACT_APP_GRPC_HOST"
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
